static const char *DefaultLanguageStringTable[SYS_UI_MSG_COUNT]={
	"No Playstation 2 memory cards detected.",
	"Memory Cards were detected in both slot 1 and 2.\n\nSelect the target memory card.",
	"FMCB will be installed onto the memory card in slot 1. Continue?",
	"FMCB will be installed onto the memory card in slot 2. Continue?",
	"FHDB will be installed onto the Harddisk Drive. Continue?",
	"Select installation type:",
	"Cache initialization failed.",
	"Existing FMCB CNF found!\nDo you want to keep it?",
	"Existing FHDB CNF found!\nDo you want to keep it?",
	"Cleanup failed.",
	"The installation was cleaned up successfully.",
	"Installation failed.",
	"Installation completed.",
	"FMCB on the memory card in slot 1 will be cleaned up. Continue?",
	"FMCB on the memory card in slot 2 will be cleaned up. Continue?",
	"FHDB on the Harddisk Drive will be cleaned up. Continue?",
	"The memory card in slot 1 will be formatted.\n\nContinue?",
	"The memory card in slot 2 will be formatted.\n\nContinue?",
	"Format failed to complete.",
	"Format complete.",
	"The memory card in slot 1 will be dumped.\n\nContinue?",
	"The memory card in slot 2 will be dumped.\n\nContinue?",
	"Memory card dumping failed.",
	"Memory card dumped.",
	"The memory card in slot 1 will be restored.\n\nContinue?",
	"The memory card in slot 2 will be restored.\n\nContinue?",
	"Memory card restoration failed.",
	"Memory card restored.",
	"Multi-installation required, but not found on card.",
	"Multi-installation detected!\nPlease uninstall first.",
	"Failed to calculate free space on card.",
	"Insufficient free space on card.",
	"Insufficient free space on the HardDisk Drive.",
	"Insufficient free space on in the APPS partition.",
	"Formatting memory card.\n\nPlease do not switch off the power or remove the card.",
	"Cleaning up memory card.\n\nPlease do not switch off the power or remove the card.",
	"Uninstalling FHDB.\n\nPlease do not switch off the power or disconnect the HDD unit.",
	"Read error.\nPlease check your installation media.",
	"Write error.\nPlease check your memory card.",
	"Read error.\nPlease check your memory card.",
	"Write error.\nPlease check your Harddisk Drive.",
	"Write error.\nPlease check your installation media.",
	"Out of memory.",
	"File not found.\nPlease check your installation media.",
	"Stop dumping memory card?",
	"Stop restoring memory card?",
	"Failed to create crosslinked files.",
	"Failed to bind MagicGate file to Memory Card.",
	"Can't remove multi-installation made by an incompatible installer.",
	"Install FMCB for this console.",
	"Install FMCB for all consoles.",
	"Uninstall FMCB.",
	"Downgrade a multi-installation to a normal installation.",
	"Format memory card.",
	"Dump memory card contents to file.",
	"Flash memory card contents from file.",
	"Install FMCB (PSX) on this memory card.",
	"Install FHDB for this console.",
	"Uninstall FHDB.",
	"Exit program.",
	"The HardDisk Drive (HDD) unit has a problem.\nPlease run a disk check first.",
	"S.M.A.R.T. has reported that the HardDisk Drive (HDD) unit has failed.\n\nThe HDD unit must be replaced.",
	"This console does not support FMCB.\n\nHowever, you can still make installations with it.",
	"While the multi-installation can boot on all PlayStation 2 consoles with the least space requirements, it goes against the design of the Memory Card by introducing controlled filesystem corruption.\n\nIt is hence strongly recommended to create a normal installation instead.",
	"Quit program?",
	"The HardDisk Drive (HDD) unit is not formatted. Format?\nWarning: All data will be erased.",
	"Failed to format the HardDisk Drive (HDD) unit.",
};

static const char *DefaultLanguageLabelStringTable[SYS_UI_LBL_COUNT]={
	"OK",
	"Cancel",
	"Yes",
	"No",
	"Next",
	"Back",
	"Enabled",
	"Disabled",
	"Toggle option",
	"Select field",
	"Warning",
	"Error",
	"Information",
	"Confirmation",
	"Slot 1",
	"Slot 2",
	"Memory Card",
	"HDD",
	"Please wait",
	"Now installing...",
	"Now dumping...",
	"Now restoring...",
	"Normal",
	"Cross-model",
	"Cross-regional",
	"Rate:",
	"Time\nremaining:",
	"Install",
	"Multi-install",
	"Uninstall FMCB",
	"Uninstall MI",
	"Format MC",
	"Dump MC",
	"Restore MC",
	"Install FMCB (PSX)",
	"Install FHDB",
	"Uninstall FHDB",
	"Exit",
	"B",
	"KB",
	"MB",
	"GB",
	"TB",
	"B/s",
	"KB/s",
	"MB/s",
	"Available space:",
	"Required space:",
	"Main Menu",
	"Extras Menu",
	"Memory Card Menu",
};
