# messege file
# English

# MSG_RETURN_MENU
#Press X to return to the main menu.
!Press X to return to the main menu.

# MSG_MENU_DATE
#TIME 
!TIME 

# MSG_MENU_BATTERY
#battery LifePercent:%3d%% LifeTime:%3dmin.
!battery LifePercent:%3d%% LifeTime:%3dmin.

# MSG_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d          

# MSG_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d          

# MSG_MAIN_MENU_0
#Graphics and Sound options
!Graphics and Sound options

# MSG_MAIN_MENU_1
#Load state from slot: %d
!Load state from slot: %d

# MSG_MAIN_MENU_2
#Save state to slot: %d
!Save state to slot: %d

# MSG_MAIN_MENU_3
#Savestate options
!Savestate options

# MSG_MAIN_MENU_4
#Configure gamepad input
!Configure gamepad input

# MSG_MAIN_MENU_5
#Configure analog input
!Configure analog input

# MSG_MAIN_MENU_6
#Cheats and Miscellaneous options
!Cheats and Miscellaneous options

# MSG_MAIN_MENU_7
#Load new game
!Load new game

# MSG_MAIN_MENU_8
#Restart game
!Restart game

# MSG_MAIN_MENU_9
#Return to game
!Return to game

# MSG_MAIN_MENU_10
#Exit gpSP
!Exit gpSP

# MSG_MAIN_MENU_HELP_0
#Select to set display parameters and frameskip behavior,\n
#audio on/off, audio buffer size, and audio filtering.
!Select to set display parameters and frameskip behavior,\n
!#audio on/off, audio buffer size, and audio filtering.

# MSG_MAIN_MENU_HELP_1
#Select to load the game state from the current slot for this game,\n
#if it exists (see the extended menu for more information)\n
#Press left + right to change the current slot.
!Select to load the game state from the current slot for this game,\n
!if it exists (see the extended menu for more information)\n
!Press left + right to change the current slot.

# MSG_MAIN_MENU_HELP_2
#Select to save the game state to the current slot for this game.\n
#See the extended menu for more information.\n
#Press left + right to change the current slot.
!Select to save the game state to the current slot for this game.\n
!See the extended menu for more information.\n
!Press left + right to change the current slot.

# MSG_MAIN_MENU_HELP_3
#Select to enter a menu for loading, saving, and viewing the\n
#currently active savestate for this game (or to load a savestate\n
#file from another game)
!Select to enter a menu for loading, saving, and viewing the\n
!currently active savestate for this game (or to load a savestate\n
!file from another game)

# MSG_MAIN_MENU_HELP_4
#Select to change the in-game behavior of the PSP buttons and d-pad.
!Select to change the in-game behavior of the PSP buttons and d-pad.

# MSG_MAIN_MENU_HELP_5
#Select to change the in-game behavior of the PSP analog nub.
!Select to change the in-game behavior of the PSP analog nub.

# MSG_MAIN_MENU_HELP_6
#Select to manage cheats, set backup behavior, and set device clock\n
#speed.
!Select to manage cheats, set backup behavior, and set device clock\n
!speed.

# MSG_MAIN_MENU_HELP_7
#Select to load a new game (will exit a game if currently playing).
!Select to load a new game (will exit a game if currently playing).

# MSG_MAIN_MENU_HELP_8
#Select to reset the GBA with the current game loaded.
!Select to reset the GBA with the current game loaded.

# MSG_MAIN_MENU_HELP_9
#Select to exit this menu and resume gameplay.
!Select to exit this menu and resume gameplay.

# MSG_MAIN_MENU_HELP_10
#Select to exit gpSP and return to the PSP XMB/loader.
!Select to exit gpSP and return to the PSP XMB/loader.

# MSG_G_S_MENU_0
#Display scaling: %s
!Display scaling: %s

# MSG_G_S_MENU_1
#Screen filtering: %s
!Screen filtering: %s

# MSG_G_S_MENU_2
#Frameskip type: %s
!Frameskip type: %s

# MSG_G_S_MENU_3
#Frameskip value: %d
!Frameskip value: %d

# MSG_G_S_MENU_4
#Framskip variation: %s
!Framskip variation: %s

# MSG_G_S_MENU_5
#Audio output: %s
!Audio output: %s

# MSG_G_S_MENU_6
#Audio buffer: %s
!Audio buffer: %s

# MSG_G_S_MENU_7
#screen shot
!screen shot

# MSG_G_S_MENU_8
#Back
!Back

# MSG_G_S_MENU_9
#TV output ratio : %s
!TV output ratio : %s

# MSG_G_S_MENU_10
#TV video mode   : %s
!TV video mode   : %s

# MSG_G_S_MENU_HELP_0
#Determines how the GBA screen is resized in relation to the entire\n
#screen. Select unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
#aspect ratio scaled to fill the height of the PSP screen, and\n
#fullscreen to fill the entire PSP screen.
!Determines how the GBA screen is resized in relation to the entire\n
!screen. Select unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
!aspect ratio scaled to fill the height of the PSP screen, and\n
!fullscreen to fill the entire PSP screen.

# MSG_G_S_MENU_HELP_1
#Determines whether or not bilinear filtering should be used when\n
#scaling the screen. Selecting this will produce a more even and\n
#smooth image, at the cost of being blurry and having less vibrant\n
#colors.
!Determines whether or not bilinear filtering should be used when\n
!scaling the screen. Selecting this will produce a more even and\n
!smooth image, at the cost of being blurry and having less vibrant\n
!colors.

# MSG_G_S_MENU_HELP_2
#Determines what kind of frameskipping should be employed.\n
#Frameskipping may improve emulation speed of many games.\n
#Off: Do not skip any frames.\n
#Auto: Skip up to N frames (see next option) as needed.\n
#Manual: Always render only 1 out of N + 1 frames.
!Determines what kind of frameskipping should be employed.\n
!Frameskipping may improve emulation speed of many games.\n
!Off: Do not skip any frames.\n
!Auto: Skip up to N frames (see next option) as needed.\n
!Manual: Always render only 1 out of N + 1 frames.

# MSG_G_S_MENU_HELP_3
#For auto frameskip, determines the maximum number of frames that\n
#are allowed to be skipped consecutively.\n
#For manual frameskip, determines the number of frames that will\n
#always be skipped.
!For auto frameskip, determines the maximum number of frames that\n
!are allowed to be skipped consecutively.\n
!For manual frameskip, determines the number of frames that will\n
!always be skipped.

# MSG_G_S_MENU_HELP_4
#If objects in the game flicker at a regular rate certain manual\n
#frameskip values may cause them to normally disappear. Change this\n
#value to 'random' to avoid this. Do not use otherwise, as it tends to\n
#make the image quality worse, especially in high motion games.
!If objects in the game flicker at a regular rate certain manual\n
!frameskip values may cause them to normally disappear. Change this\n
!value to 'random' to avoid this. Do not use otherwise, as it tends to\n
!make the image quality worse, especially in high motion games.

# MSG_G_S_MENU_HELP_5
#Select 'no' to turn off all audio output. This will not result in a\n
#significant change in performance.
!Select 'no' to turn off all audio output. This will not result in a\n
!significant change in performance.

# MSG_G_S_MENU_HELP_6
#Set the size (in bytes) of the audio buffer. Larger values may result\n
#in slightly better performance at the cost of latency; the lowest\n
#value will give the most responsive audio.\n
#This option requires gpSP to be restarted before it will take effect.
!Set the size (in bytes) of the audio buffer. Larger values may result\n
!in slightly better performance at the cost of latency; the lowest\n
!value will give the most responsive audio.\n
!This option requires gpSP to be restarted before it will take effect.

# MSG_G_S_MENU_HELP_7
#screen shot
!screen shot

# MSG_G_S_MENU_HELP_8
#Return to the main menu.
!Return to the main menu.

# MSG_G_S_MENU_HELP_9
#TV output ratio
#
#
#
!TV output ratio
!
!
!

# MSG_G_S_MENU_HELP_10
#TV output interlace
#
#
#
!TV output interlace
!
!
!

# MSG_STATE_MENU_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_NONE_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#----------  --/--/----  --:--:--          
!----/--/--  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#----------  --/--/----  --:--:--          
!----------  --/--/----  --:--:--          

# MSG_STATE_MENU_DATE_NONE_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#----------  --/--/----  --:--:--          
!----------  --/--/----  --:--:--          

# MSG_STATE_MENU_STATE_NONE
#No savestate exists for this slot.
!No savestate exists for this slot.

# MSG_STATE_MENU_TITLE
#Savestate options:
!Savestate options:

# MSG_STATE_MENU_0
#Load savestate from current slot
!Load savestate from current slot

# MSG_STATE_MENU_1
#Save savestate to current slot
!Save savestate to current slot

# MSG_STATE_MENU_2
#Load savestate from file
!Load savestate from file

# MSG_STATE_MENU_3
#Current savestate slot: %d
!Current savestate slot: %d

# MSG_STATE_MENU_4
#Back
!Back

# MSG_STATE_MENU_HELP_0
#Select to load the game state from the current slot for this game.\n
#Press left + right to change the current slot.
!Select to load the game state from the current slot for this game.\n
!Press left + right to change the current slot.

# MSG_STATE_MENU_HELP_1
#Select to save the game state to the current slot for this game.\n
#Press left + right to change the current slot.
!Select to save the game state to the current slot for this game.\n
!Press left + right to change the current slot.

# MSG_STATE_MENU_HELP_2
#Restore gameplay from a savestate file.\n
#Note: The same file used to save the state must be present.\n
!Restore gameplay from a savestate file.\n
!Note: The same file used to save the state must be present.\n

# MSG_STATE_MENU_HELP_3
#Change the current savestate slot.\n
!Change the current savestate slot.\n

# MSG_STATE_MENU_HELP_4
#Return to the main menu.
!Return to the main menu.

# MSG_PAD_MENU_0
#D-pad up     : %s
!D-pad up     : %s

# MSG_PAD_MENU_1
#D-pad down   : %s
!D-pad down   : %s

# MSG_PAD_MENU_2
#D-pad left   : %s
!D-pad left   : %s

# MSG_PAD_MENU_3
#D-pad right  : %s
!D-pad right  : %s

# MSG_PAD_MENU_4
#Circle       : %s
!Circle       : %s

# MSG_PAD_MENU_5
#Cross        : %s
!Cross        : %s

# MSG_PAD_MENU_6
#Square       : %s
!Square       : %s

# MSG_PAD_MENU_7
#Triangle     : %s
!Triangle     : %s

# MSG_PAD_MENU_8
#Left Trigger : %s
!L1           : %s

# MSG_PAD_MENU_9
#Right Trigger: %s
!R1           : %s

# MSG_PAD_MENU_10
#Start        : %s
!Start        : %s

# MSG_PAD_MENU_11
#Select       : %s
!Select       : %s

# MSG_PAD_MENU_12
#Back
!Back

# MSG_PAD_MENU_14
#Left Trigger : %s
!L2           : %s

# MSG_PAD_MENU_15
#Right Trigger: %s
!R2           : %s

# MSG_PAD_MENU_16
#Left Trigger : %s
!L3           : %s

# MSG_PAD_MENU_17
#Right Trigger: %s
!R3           : %s

# MSG_PAD_MENU_HELP_0
#Return to the main menu.
!Return to the main menu.

#PADの設定 コンフィグ

# MSG_PAD_MENU_CFG_0
#UP
!UP

# MSG_PAD_MENU_CFG_1
#DOWN
!DOWN

# MSG_PAD_MENU_CFG_2
#LEFT
!LEFT

# MSG_PAD_MENU_CFG_3
#RIGHT
!RIGHT

# MSG_PAD_MENU_CFG_4
#A
!A

# MSG_PAD_MENU_CFG_5
#B
!B

# MSG_PAD_MENU_CFG_6
#L
!L

# MSG_PAD_MENU_CFG_7
#R
!R

# MSG_PAD_MENU_CFG_8
#START
!START

# MSG_PAD_MENU_CFG_9
#SELECT
!SELECT

# MSG_PAD_MENU_CFG_10
#MENU
!MENU

# MSG_PAD_MENU_CFG_11
#FASTFORWARD
!FASTFORWARD

# MSG_PAD_MENU_CFG_12
#LOAD STATE
!LOAD STATE

# MSG_PAD_MENU_CFG_13
#SAVE STATE
!SAVE STATE

# MSG_PAD_MENU_CFG_14
#RAPIDFIRE A
!RAPIDFIRE A

# MSG_PAD_MENU_CFG_15
#RAPIDFIRE B
!RAPIDFIRE B

# MSG_PAD_MENU_CFG_16
#RAPIDFIRE L
!RAPIDFIRE L

# MSG_PAD_MENU_CFG_17
#RAPIDFIRE R
!RAPIDFIRE R

# MSG_PAD_MENU_CFG_18
#VOLUME UP
!VOLUME UP

# MSG_PAD_MENU_CFG_19
#VOLUME DOWN
!VOLUME DOWN

# MSG_PAD_MENU_CFG_20
#DISPLAY FPS
!DISPLAY FPS

# MSG_PAD_MENU_CFG_21
#NOTHING
!NOTHING

# MSG_PAD_MENU_HELP_0
#Up button on GBA d-pad.
!Up button on GBA d-pad.

# MSG_PAD_MENU_HELP_1
#Down button on GBA d-pad.
!Down button on GBA d-pad.

# MSG_PAD_MENU_HELP_2
#Left button on GBA d-pad.
!Left button on GBA d-pad.

# MSG_PAD_MENU_HELP_3
#Right button on GBA d-pad.
!Right button on GBA d-pad.

# MSG_PAD_MENU_HELP_4
#A button on GBA.
!A button on GBA.

# MSG_PAD_MENU_HELP_5
#B button on GBA.
!B button on GBA.

# MSG_PAD_MENU_HELP_6
#Left shoulder button on GBA.
!Left shoulder button on GBA.

# MSG_PAD_MENU_HELP_7
#Right shoulder button on GBA.
!Right shoulder button on GBA.

# MSG_PAD_MENU_HELP_8
#Start button on GBA.
!Start button on GBA.

# MSG_PAD_MENU_HELP_9
#Select button on GBA.
!Select button on GBA.

# MSG_PAD_MENU_HELP_10
#Brings up the options menu.
!Brings up the options menu.

# MSG_PAD_MENU_HELP_11
#Toggles fastforward on/off (don't expect it to do much or anything)
!Toggles fastforward on/off (don't expect it to do much or anything)

# MSG_PAD_MENU_HELP_12
#Loads the game state from the current slot.
!Loads the game state from the current slot.

# MSG_PAD_MENU_HELP_13
#Saves the game state to the current slot.
!Saves the game state to the current slot.

# MSG_PAD_MENU_HELP_14
#Rapidly press/release the A button on GBA.
!Rapidly press/release the A button on GBA.

# MSG_PAD_MENU_HELP_15
#Rapidly press/release the B button on GBA.
!Rapidly press/release the B button on GBA.

# MSG_PAD_MENU_HELP_16
#Rapidly press/release the L shoulder button on GBA.
!Rapidly press/release the L shoulder button on GBA.

# MSG_PAD_MENU_HELP_17
#Rapidly press/release the R shoulder button on GBA.
!Rapidly press/release the R shoulder button on GBA.

# MSG_PAD_MENU_HELP_18
#Increases the volume.
!Increases the volume.

# MSG_PAD_MENU_HELP_19
#Decreases the volume.
!Decreases the volume.

# MSG_PAD_MENU_HELP_20
#Displays virtual/drawn frames per second.
!Displays virtual/drawn frames per second.

# MSG_PAD_MENU_HELP_21
#Does nothing.
!Does nothing.

# MSG_A_PAD_MENU_0
#Analog up   : %s
!Analog up   : %s

# MSG_A_PAD_MENU_1
#Analog down : %s
!Analog down : %s

# MSG_A_PAD_MENU_2
#Analog left : %s
!Analog left : %s

# MSG_A_PAD_MENU_3
#Analog right: %s
!Analog right: %s

# MSG_A_PAD_MENU_4
#Enable analog: %s
!Enable analog: %s

# MSG_A_PAD_MENU_5
#Analog sensitivity: %d
!Analog sensitivity: %d

# MSG_A_PAD_MENU_6
#Back
!Back

# MSG_A_PAD_MENU_HELP_0
#Select 'no' to block analog input entirely.
!Select 'no' to block analog input entirely.

# MSG_A_PAD_MENU_HELP_1
#Determine sensitivity/responsiveness of the analog input.\n
#Lower numbers are less sensitive.
!Determine sensitivity/responsiveness of the analog input.\n
!Lower numbers are less sensitive.

# MSG_A_PAD_MENU_HELP_2
#Return to the main menu.
!Return to the main menu.

# MSG_CHEAT_MENU_NON_LOAD
#cheat %d (none loaded)
!cheat %d (none loaded)

# MSG_CHEAT_MENU_0
#cheat %d (%s): %%s
!cheat %d (%s): %%s

# MSG_CHEAT_MENU_1
#Load Cheat File
!Load Cheat File

# MSG_CHEAT_MENU_2
#Clock speed: %s
!Clock speed: %s

# MSG_CHEAT_MENU_3
#Update backup: %s
!Update backup: %s

# MSG_CHEAT_MENU_4
#Back
!Back

# MSG_CHEAT_MENU_HELP_0
#Activate/deactivate this cheat code.
!Activate/deactivate this cheat code.

# MSG_CHEAT_MENU_HELP_1
# Load Cheat File
! Load Cheat File

# MSG_CHEAT_MENU_HELP_2
#Change the clock speed of the device. Higher clock speed will yield\n
#better performance, but will use drain battery life further.
!Change the clock speed of the device. Higher clock speed will yield\n
!better performance, but will use drain battery life further.

# MSG_CHEAT_MENU_HELP_3
#Determines when in-game save files should be written back to\n
#memstick. If set to 'automatic' writebacks will occur shortly after\n
#the game's backup is altered. On 'exit only' it will only be written\n
#back when you exit from this menu (NOT from using the home button).\n
#Use the latter with extreme care.
!Determines when in-game save files should be written back to\n
!memstick. If set to 'automatic' writebacks will occur shortly after\n
!the game's backup is altered. On 'exit only' it will only be written\n
!back when you exit from this menu (NOT from using the home button).\n
!Use the latter with extreme care.

# MSG_CHEAT_MENU_HELP_4
#Return to the main menu.
!Return to the main menu.

# MSG_NON_LOAD_GAME
#No game loaded yet.
!No game loaded yet.

# MSG_WDAY_0
#Sunday
!Sunday

# MSG_WDAY_1
#Monday
!Monday

# MSG_WDAY_2
#Tuesday
!Tuesday

# MSG_WDAY_3
#Wednesday
!Wednesday

# MSG_WDAY_4
#Thursday
!Thursday

# MSG_WDAY_5
#Friday
!Friday

# MSG_WDAY_6
#Saturday
!Saturday

# MSG_YES
#yes
!yes

# MSG_NO
#no
!no

# MSG_ENABLED
#enabled
!enabled

# MSG_DISABLED
#disabled
!disabled

# MSG_SCALE_UNSCALED
#unscaled 3:2
!unscaled

# MSG_SCALE_SCALED
#scaled 3:2
!Scale2x

# MSG_SCALE_FULL
#fullscreen 16:9
!Super2xSaI

# MSG_SCN_OPT1
#option 1
!SuperEagle

# MSG_SCN_OPT2
#option 2
!2xSaI

# MSG_FS_AUTO
#automatic
!automatic

# MSG_FS_MANUAL
#manual
!manual

# MSG_FS_OFF
#off
!off

# MSG_FS_UNIFORM
#uniform
!uniform

# MSG_FS_RAMDOM
#random
!random

# MSG_SB_2048
#2048 bytes
!2048 bytes

# MSG_SB_3072
#3072 bytes
!3072 bytes

# MSG_SB_4096
#4096 bytes
!4096 bytes

# MSG_SB_5120
#5120 bytes
!5120 bytes

# MSG_SB_6144
#6144 bytes
!6144 bytes

# MSG_SB_7168
#7168 bytes
!7168 bytes

# MSG_SB_8192
#8192 bytes
!8192 bytes

# MSG_SB_9216
#9216 bytes
!9216 bytes

# MSG_SB_10240
#10240 bytes
!10240 bytes

# MSG_SB_11264
#11264 bytes
!11264 bytes

# MSG_SB_12288
#12288 bytes
!12288 bytes

# MSG_BK_EXITONLY
#Exit only
!Exit only

# MSG_BK_AUTO
#Automatic
!Automatic

# MSG_CLK_33
#33MHz
!33MHz

# MSG_CLK_66
#66MHz
!66MHz

# MSG_CLK_100
#100MHz
!100MHz

# MSG_CLK_133
#133MHz
!133MHz

# MSG_CLK_166
#166MHz
!166MHz

# MSG_CLK_200
#200MHz
!200MHz

# MSG_CLK_233
#233MHz
!233MHz

# MSG_CLK_266
#266MHz
!266MHz

# MSG_CLK_300
#300MHz
!300MHz

# MSG_CLK_333
#333MHz
!333MHz

# MSG_SS_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%02d_%02d_%04d_%s%02d_%02d_%02d_%03d
!%04d_%02d_%02d_%s%02d_%02d_%02d_%03d

# MSG_SS_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_SS_FMT_3
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_ERR_BIOS_1
#Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
#correctly. Make sure to get an authentic one (search the web,\n
#beg other people if you want, but don't hold me accountable\n
#if you get hated or banned for it), it'll be exactly 16384\n
#bytes large and should have the following md5sum value:\n\n
!Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
!correctly. Make sure to get an authentic one (search the web,\n
!beg other people if you want, but don't hold me accountable\n
!if you get hated or banned for it), it'll be exactly 16384\n
!bytes large and should have the following md5sum value:\n\n

# MSG_ERR_BIOS_2
#a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
#Other BIOS files might work either partially completely, I\n
#really don't know.\n\n
#When you do get it name it gba_bios.bin and put it in the\n
#same directory as this EBOOT.\n\n
#Good luck. Press any button to exit.\n
!a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
!Other BIOS files might work either partially completely, I\n
!really don't know.\n\n
!When you do get it name it gba_bios.bin and put it in the\n
!same directory as this EBOOT.\n\n
!Good luck. Press any button to exit.\n

# MSG_ERR_BIOS_MD5
#This BIOS is not regular.\n
#There is a possibility of various trouble.\n\n
#Please use regular BIOS.\n
!This BIOS is not regular.\n
!There is a possibility of various trouble.\n\n
!Please use regular BIOS.\n

# MSG_R_4_3
#ratio 4:3
!ratio 3:2

# MSG_R_16_9
#ratio 16:9
!fullscreen

# MSG_I_NON
#progressive
#!progressive

# MSG_I_ON
#interlace
#!interlace

# MSG_V_NTSC
#NTSC
!NTSC

# MSG_V_DTV_480P
#480P
!480P

# MSG_V_DTV_720P
#720P
!720P

#MSG_DTV_1080I
#1080I
!1080I

# MSG_INIT_END
#Initialization end
!Initialization end

# MSG_LOAD_STATE
#Load State.
!Load State.

# MSG_LOAD_STATE_END
#Load State End.
!Load State End.

# MSG_SAVE_STATE
#Save State.
!Save State.

# MSG_SAVE_STATE_END
#Save State End.
!Save State End.

# MSG_CHEAT_MENU_5
#cheat page: %d
!cheat page: %d

# MSG_CHEAT_MENU_HELP_5
#cheat page
!cheat page

# MSG_CHEAT_MENU_6
#Enable HOME: %s
!Enable HOME: %s

# MSG_CHEAT_MENU_HELP_6
#Enable HOME
!Enable HOME

# MSG_PAD_MENU_13,
#Use dafault map : %s
!Use dafault map : %s

# MSG_PAD_MENU_HELP13,
#Use dafault map
!Use dafault map

